### ISSUE TITLE
RuntimeWarning: Mean of empty slice.  RuntimeWarning: invalid value encountered in double_scalars   

### ISSUE THREAD

**Issue by magedhelmy1** [rafaelpadilla/review_object_detection_metrics#27]
The error message is
```

(metrics) maged-ubuntu-20@magedubuntu20-virtual-machine:~/Desktop/PyCharm_Projects/16_metrics_measurement$ python run.py
/home/maged-ubuntu-20/anaconda3/envs/metrics/lib/python3.9/site-packages/numpy/core/fromnumeric.py:3372: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/maged-ubuntu-20/anaconda3/envs/metrics/lib/python3.9/site-packages/numpy/core/_methods.py:170: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
/home/maged-ubuntu-20/anaconda3/envs/metrics/lib/python3.9/site-packages/numpy/core/fromnumeric.py:3372: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/maged-ubuntu-20/anaconda3/envs/metrics/lib/python3.9/site-packages/numpy/core/_methods.py:170: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
/home/maged-ubuntu-20/anaconda3/envs/metrics/lib/python3.9/site-packages/numpy/core/fromnumeric.py:3372: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/maged-ubuntu-20/anaconda3/envs/metrics/lib/python3.9/site-packages/numpy/core/_methods.py:170: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
```

Here is my ground truth file

```
0 412 130 95 104
0 521 82 126 106
0 521 314 226 155
0 820 372 123 101
0 473 616 101 120
0 956 350 98 105
0 177 581 110 88
0 680 638 125 120
0 958 611 135 113
```

Here is my predicted truth file

```
0 0.99 699 1012 778 1079
0 0.99 529 1014 591 1079
0 0.99 0 997 77 1079
0 0.99 77 1003 251 1079
0 0.99 367 1027 454 1079
0 0.99 1458 975 1579 1077
0 0.99 1274 882 1425 1038
0 0.99 952 925 1056 1033
0 0.99 500 978 554 1026
0 0.99 1788 952 1865 1021
0 0.99 733 913 877 1004
0 0.99 196 901 305 998
0 0.99 1840 870 1919 965
```

As you can see all accuracy score is zero 

![Screenshot from 2021-03-09 20-45-59](https://user-images.githubusercontent.com/63347261/110528553-8ece1200-8118-11eb-9968-ec548f154ecf.png)

Can someone please help with how to fix this issue?

**Comment by rafaelpadilla** [comment]
@magedhelmy1 ,

The results are correct. There is no overlap between any ground-truth and detected bounding boxes (as you can see below):
![res](https://user-images.githubusercontent.com/31217453/110543602-4b1fdc00-8109-11eb-9a49-1f8e1fd0e748.png)

Please, consider closing this issue if your problem was solved.

**Comment by magedhelmy1** [comment]
@rafaelpadilla I randomly copied these from different two files just to demonstrate an example.

However, when you put these 2 files into the software, it crashes and gives `RuntimeWarning: Mean of empty slice. RuntimeWarning: invalid value encountered in double_scalars`. It's not supposed to crash, but rather just give 0 as an output. DId it also crash on your side?

**Comment by rafaelpadilla** [comment]
Hi @magedhelmy1 ,

This warning is due to an attempt to get the mean of an empty list (`np.mean([])`). As there was no overlap, this list happened to be empty.

This shouldn't be a problem. My guess is that there might be some configuration in your python `warning` library that it does not tolerate warnings, making the application crash.

I changed the code, to check if the lists are empty before taking the mean. Please, update your code and let me know if it is now solved. :)

**Comment by magedhelmy1** [comment]
Thanks for maintaining your repo! Makes a huge difference.

**Comment by rafaelpadilla** [comment]
@magedhelmy1,

Excellent! :)

Did it solve your problem? If so, please close this issue.
