### ISSUE TITLE
Confusion in IoU computation for tubes

### ISSUE THREAD

**Issue by TheShadow29** [rafaelpadilla/review_object_detection_metrics#54]
Hi. Thanks for the clean repository!

I am slightly confused in this part of the code: https://github.com/rafaelpadilla/review_object_detection_metrics/blob/main/src/evaluators/tube_evaluator.py#L217

Shouldn't it be `iou = inter / union` ?

**Comment by rafaelpadilla** [comment]
Hi @TheShadow29 ,

The [computed iou]([url](https://github.com/rafaelpadilla/review_object_detection_metrics/blob/main/src/evaluators/tube_evaluator.py#L217)) is correct. The union computed [here](https://github.com/rafaelpadilla/review_object_detection_metrics/blob/main/src/evaluators/tube_evaluator.py#L211) actually considers both tubes.

`union = A + B`, which is also considering the intersection between them twice. That's why, to compute the iou, the intersection must be subtracted. So we can have:
![image](https://user-images.githubusercontent.com/31217453/120079529-ae773580-c08a-11eb-8028-6ca07397d1e7.png)

I hope it was clear. :)

**Comment by TheShadow29** [comment]
Ah! I missed that! Thanks a lot!
