### ISSUE TITLE
invalid image directory

### ISSUE THREAD

**Issue by Mshz2** [rafaelpadilla/review_object_detection_metrics#6]
Hi

I have loaded ground truth labels as pascal VOC (xml) and their images and it successfully plotted them (on show ground truth statics). I also made my detection labels as the toyexample for classid confidence  left top height width (absolute) as below:
0 0.99 37 143 98 206
and I just simply gave the directory of all detections. however, the GUI give the error of "For the selected annotation type, it is necessary to inform a directory with the dataset images. Directory is empty or does not have valid images." 

So I just copied all the images (as the ones I gave in first part) to the detection labels directory. But it still give me the mentioned error. My images are 300*300 png frames.

Thanks for support.

**Comment by rafaelpadilla** [comment]
Hi @Mshz2 ,

Could you please, zip a couple images, detections and ground-truths and attach here, so I can try to replicate this problem?

Thank you

**Comment by Mshz2** [comment]
> Hi @Mshz2 ,
> 
> Could you please, zip a couple images, detections and ground-truths and attach here, so I can try to replicate this problem?
> 
> Thank you

[test.zip](https://github.com/rafaelpadilla/review_object_detection_metrics/files/5939603/test.zip)
Thanks alot

**Comment by Mshz2** [comment]
> Hi @Mshz2 ,
> 
> Could you please, zip a couple images, detections and ground-truths and attach here, so I can try to replicate this problem?
> 
> Thank you

Thanks a lot. 
[test.zip](https://github.com/rafaelpadilla/review_object_detection_metrics/files/5939651/test.zip)
btw, I had to delete images and give just a blank white frame as I am not allowed to share images. But thanks for the support, I hope this would be usefull.

**Comment by rafaelpadilla** [comment]
Dear @Mshz2 ,

I noticed that your ground-truth files (XML) name the objects class as "pore" (`<name>pore</name>`), and your detection files identifies the object classes as "0" (all your detection files start with "0"). So this "0" can be either the `id` or the `name` of the class.

First thing you have to do is: separate your files into 3 different folders: groundtruths, detections and images.

Then, please, update your code with the fixes I have just made. The error messages were not telling you the error correctly.

Now you have two choices. The first one is the easiest one :)

-----------------

**1st option:**
Make a txt file as this one [class.txt](https://github.com/rafaelpadilla/review_object_detection_metrics/files/5939691/class.txt)
As you can see, in its first line (line 0) I put the name of your object ("spore"). This way the program will know that your detection files are representing the class "0" with the name in the line 0 of the file ("spore").

In the interface you have to choose:
Ground truth:
**Annotations**: Choose the directory where your (.xml) files are.
**Images** (optional): Choose the directory where your images are.
**Coordinate type**: Pick the option "PASCAL VOC (.xml)
**Output**: Choose a directory where the outputs will be saved.

Detections:
**Annotations**: Choose the directory where your detections (.txt) files are.
**Classes (*) **: Point to the `class.txt` file.
**Coordinate type**: Pick the option "<class_id> <confidence> <left> <top> <right> <bottom> (ABSOLUTE)"
**Output**: Choose a directory where the outputs will be saved.

-----------------

**2nd option:**
Change all detection (.txt) files replacing the first element "0" by "pore".
Example:
Now you have: `0 0.99 37 143 98 206`
Change it to: `pore 0.99 37 143 98 206`

In the interface you have to choose:
Ground truth:
**Annotations**: Choose the directory where your (.xml) files are.
**Images**: (optional) Choose the directory where your images are.
**Coordinate type**: Pick the option "PASCAL VOC (.xml)

Detections:
**Annotations**: Choose the directory where your (.txt) files are.
**Classes (*) **: Leave it blank, because you now included the name of the classes in your detection files.
**Coordinate type**: Pick the option "<class_name> <confidence> <left> <top> <right> <bottom> (ABSOLUTE)"

-----------------

In both cases, if you inserted the directory with the images, you can visualize your bounding boxes in the statistics.

I hope it helps.

Best regards

**Comment by rafaelpadilla** [comment]
@Mshz2 

No problem you had to delete the images. I totally understand it. :) 

I hope the instructions in the previous message helps you. Let me know if you got it working.

**Comment by Mshz2** [comment]
@rafaelpadilla thanks aloooot for your effort. 
I did as you said but unfortunately I get everything 0.
![eval](https://user-images.githubusercontent.com/63469924/107160289-aa1cf480-6995-11eb-8bc0-9154b225e397.png)

**Comment by rafaelpadilla** [comment]
@Mshz2 
This is strange. With the files you provided, I obtain different results:

![image](https://user-images.githubusercontent.com/31217453/107160421-d6744900-6974-11eb-8dba-dfab4dd7ae4d.png)

Have you updated the repository? I updated it with few changes.

You dont have to show them here, but if you click on "show detections statistics", are you able to see the images with the bounding boxes?

**Comment by Mshz2** [comment]
@rafaelpadilla forget above message :) seems like when I did as second option it worked!
In first option it gave everything 0

![eval2](https://user-images.githubusercontent.com/63469924/107160478-beadbc80-6996-11eb-96fb-017156e984be.png)

**Comment by rafaelpadilla** [comment]
Great! :) 
I will close this issue now. If you have any other problem, just open another issue or reach me at linkedin.
Best regards.
