### ISSUE TITLE
instance segmentation metrics

### ISSUE THREAD

**Issue by andreaceruti** [rafaelpadilla/review_object_detection_metrics#93]
How to modify the code in order to get the same metrics but using the instance mask (polygons/RLE) instead of using the bounding boxes for IoU overlap calculation?

**Comment by rafaelpadilla** [comment]
Hi @andreaceruti 

You would have to replace the [BoundingBox.py](https://github.com/rafaelpadilla/review_object_detection_metrics/blob/main/src/bounding_box.py) and its contents to something that considers the blobs (your segmented areas).

Functions [iou](https://github.com/rafaelpadilla/review_object_detection_metrics/blob/main/src/bounding_box.py#L341), [have_intersection](https://github.com/rafaelpadilla/review_object_detection_metrics/blob/main/src/bounding_box.py#L357), [get_intersection_area](https://github.com/rafaelpadilla/review_object_detection_metrics/blob/main/src/bounding_box.py#L373), and [get_union_areas](https://github.com/rafaelpadilla/review_object_detection_metrics/blob/main/src/bounding_box.py#L373) should look at the blobs instead of the bounding box.

Also, the[coordinates](https://github.com/rafaelpadilla/review_object_detection_metrics/blob/main/src/bounding_box.py#L13) instead of being a tuple of 4 components (x,y,width,height), it should represent the contour.

**Comment by bhuvanofc** [comment]
@rafaelpadilla can you please elaborate on this. I am trying to calculate the metric for my instance segmentation results.  It would be really helpful as i have to evaluate fro my master thesis

**Comment by rafaelpadilla** [comment]
@bhuvanofc 

This code was developed for bounding boxes only. For instance segmentations, the easiest way is to transform the polygons into binary blobs and work with it.

The IOU between ground-truth A and detection B would be `(A and B)/(A or B)`. That's why, you need to change the `BoundingBox.py` file.

Unfortunately I'm busy with other projects and can't make that for you. But feel free to post here your questions. Maybe someone can help you

**Comment by Mirzyaaliii** [comment]
Hello,

@andreaceruti and @bhuvanofc, did you find any helpful solution??

I am also working on a segmentation task and I am not sure how to calculate mAP between 2 masks (i.e., ground truth and prediction).

It would be helpful if anyone can point out to useful code or give some insights.
